### ISSUE TITLE
!Питання за вашу клавиатуру!

### ISSUE THREAD

**Issue by IlyasTarpan** [medzuslovjansky/database#62]
Доброго дня!

Я писав вам тут, у Гітхабі, а також писав вам на пошту (вам повинно було прийти письмо від batirknight@gmail.com), але ви не відповили :(

Я вас питал за вашу клавиатуру на Gboard. Наскільки я знаю, ви створили свою раскладку для міжслов'янскої мови.

Річь в тому, що мені теж потрібно зробити таку клавіатуру, і був би вам дуже вдячний, якщо ви розповизьсті, як ви це зробили :)

Iз нетерпкою чекаю на вашу відповідь,
с повагою İль'яс

**Comment by noomorph** [comment]
I'll answer in the other issue you opened.

**Comment by IlyasTarpan** [comment]
Доброго дня!

Можете будь ласка поділитися контактами цього Андрєя Усачева?

> I'll answer in the other issue you opened.
